import { test, expect } from '@playwright/test';

test.describe('AstraNexus コーポレートサイト テスト', () => {
  test.beforeEach(async ({ page }) => {
    // ローカルサーバー上のトップページ（日本語版）に遷移
    await page.goto('/');
  });

  test('基本情報とSEO対策の検証（日本語版）', async ({ page }) => {
    await expect(page).toHaveTitle(/AstraNexus \| 次世代Webアプリケーション開発・SaaSエンジニアリング/);

    const metaTitle = await page.locator('meta[property="og:title"]').getAttribute('content');
    expect(metaTitle).toBe('AstraNexus | 次世代Webアプリケーション開発・SaaSエンジニアリング');

    const canonical = await page.locator('link[rel="canonical"]').getAttribute('href');
    expect(canonical).toBe('https://astranexus.dev/');

    // hreflangタグの検証
    await expect(page.locator('link[hreflang="ja"]')).toHaveAttribute('href', 'https://astranexus.dev/');
    await expect(page.locator('link[hreflang="en"]')).toHaveAttribute('href', 'https://astranexus.dev/en/');
  });

  test('ヘッダーロゴのアクセシビリティ検証', async ({ page }) => {
    const logoSvg = page.locator('#logo svg.logo-icon');
    await expect(logoSvg).toBeVisible();
    await expect(logoSvg).toHaveAttribute('role', 'img');
    await expect(logoSvg).toHaveAttribute('aria-label', 'AstraNexus ロゴ');
  });

  test('会社概要（代表取締役CEOと所在地が空欄であること）の検証', async ({ page }) => {
    const ceoCell = page.locator('table.profile-table tr:has-text("代表取締役 CEO") td');
    await expect(ceoCell).toHaveText('');

    const locationCell = page.locator('table.profile-table tr:has-text("所在地") td');
    await expect(locationCell).toHaveText('');
  });

  test('免責事項の表示検証（日本語版）', async ({ page }) => {
    const footer = page.locator('footer');
    await expect(footer).toContainText('※このウェブサイトはAIによって自動生成されたデモサイトであり、掲載されている「AstraNexus」は架空の企業です。');
  });

  test('お問い合わせセクションが非表示であることを検証', async ({ page }) => {
    const contactSection = page.locator('#contact');
    await expect(contactSection).not.toBeVisible();
  });

  test('言語切り替え（多言語対応）の検証', async ({ page }) => {
    // 1. 初期状態（日本語版）で JP がアクティブ、EN がリンクであることを検証
    const jpSwitcher = page.locator('.lang-switcher span.lang-link', { hasText: 'JP' });
    await expect(jpSwitcher).toHaveClass(/active/);

    const enSwitcher = page.locator('.lang-switcher a.lang-link', { hasText: 'EN' });
    await expect(enSwitcher).toBeVisible();
    await expect(enSwitcher).toHaveAttribute('href', '/en/');

    // 2. EN をクリックして英語版へ遷移
    await enSwitcher.click();
    await expect(page).toHaveURL(/\/en\/?/);

    // 3. 英語版のコンテンツ検証
    await expect(page).toHaveTitle(/AstraNexus \| Next-Gen Web Application Development & SaaS Engineering/);
    await expect(page.locator('h2.section-title', { hasText: 'Our Services' })).toBeVisible();

    const enDisclaimer = page.locator('footer');
    await expect(enDisclaimer).toContainText('*This website is a demo generated by AI. "AstraNexus" is a fictitious company.');

    // 4. 英語版で EN がアクティブ、JP がリンクであることを検証
    const enActive = page.locator('.lang-switcher span.lang-link', { hasText: 'EN' });
    await expect(enActive).toHaveClass(/active/);

    const jpLink = page.locator('.lang-switcher a.lang-link', { hasText: 'JP' });
    await expect(jpLink).toBeVisible();
    await expect(jpLink).toHaveAttribute('href', '/');

    // 5. JP をクリックして日本語版へ戻る
    await jpLink.click();
    await expect(page).toHaveURL(/\/$/);
  });
});
